### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by lisztmephisto** [matthewfripp/SearchBlox#11]
For like a week now SearchBlox has not been working for me, showing me an error when trying to search a player. Decided to reinstall it but when trying to drop the folder into the extensions page an error pops up telling me that the manifest file is missing or unreadable.
![manifesterror](https://user-images.githubusercontent.com/103931083/163792483-c86faa43-91a6-4c0b-8f4c-47fe31306f11.PNG)

**Comment by jacobpieee** [comment]
It has been removed from the google extensions store so that might be why it isnt working

**Comment by lisztmephisto** [comment]
It used to work even after it was taken down by just downloading it here and dragging the folder into the extensions page. But now that doesn't work anymore.

**Comment by matthewfripp** [comment]
Hi, please use the dev branch as master is deprecated. As for the reason of your error, you need to load the `chrome` folder, not the whole repo
