### ISSUE TITLE
If you close and delete this issue, it proves that all the contributors here are ignorant and have no life. I suggest you read this entire issue.

### ISSUE THREAD

**Issue by ValiantWind** [matthewfripp/SearchBlox#7]
I'm going to go straight to the point: Remove your extension from the Chrome Web Store and delete the source code. Read more below.

It's stupid that you continue to keep this extension running since its clearly obvious that it ruins the experience for Star Creators and lots of players as well.

The fact that you APPEALED to Google and that you even OPEN-SOURCED the code makes it obvious that you're TRYING to ruin the experience for others. 

If you delete this extension, you'll make the star creators and everyone else on Roblox happy. Show everyone on Roblox that all the contributors of this extension have a heart and actually care about the community.

If don't though, you're only be proving to everyone that you're heartless. I hope you're happy knowing that everyday knowing that your extension ruins everyone's experience on Roblox. 

- An Anonymous Robloxian

**Comment by mmccall0813** [comment]
this extension has more uses than stream sniping, I use it to quick join my friends when im not on my main account. Deleting this repo wont do anything, people will just re-upload the source to github or some other git site

**Comment by ValiantWind** [comment]
Thanks for replying. I appreciate. Though this extension has no use anymore though. The API endpoint you use to bypass privacy settings is now deprecated.
